version: "3.4"
services:

  zookeeper:
    image: "zookeeper:latest"
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always

  hbase:
    image: "apachedrill:latest"
    container_name: apache-drill
    environment:
      - "CLUSTERID=TESTCLUSTER"
      - "ZKHOSTS=localhost:2181"
    ports:
      - "8047:8047"
    restart: always